### ISSUE TITLE
Report an error if unable to create the results database

### ISSUE THREAD

**Issue by hillaryj** [cfpb/cfgov-crawler-app#2]
If the folder for the database doesn't exist, the db creation fails silently and all the results do not get saved.

**Comment by hillaryj** [comment]
Also, make it clear in the Readme that the database is stored in a relative path to your run location `./database/cfpb-site.db` - it's not clear now.

**Comment by mistergone** [comment]
The first issue is fixed in [this pull request](https://github.com/cfpb/cfgov-crawler-app/pull/3). I'll update the README in my next PR!
